sites:
    brandon.sitenow.uiowa.edu:
        shortname: brandon
        type: custom
        profile: sitenow
        git: git@github.com:ITS-UofIowa/brandon.sitenow.uiowa.edu.git
    rick.sitenow.uiowa.edu:
        shortname: rick
        type: custom
        profile: sitenow
        git: git@github.com:ITS-UofIowa/rick.sitenow.uiowa.edu.git
    brandonstandard.sitenow.uiowa.edu:
        shortname: brandonstandard
        type: standard
        profile: sitenow_standard_profile
    brian.sitenow.uiowa.edu:
        shortname: brian
        type: standard
        profile: sitenow_standard_profile
    hawktools.uiowa.edu:
        shortname: hawktools
        type: custom
        profile: sitenow
        git: git@github.com:/its-uofiowa/hawktools.uiowa.edu
    sitenow.uiowa.edu:
        shortname: sitenow
        type: custom
        profile: sitenow
        git: git@github.com:/its-uofiowa/sitenow.uiowa.edu
    housing.uiowa.edu:
        shortname: housing
        type: custom
        profile: sitenow
        git: git@github.com:/its-uofiowa/housing.uiowa.edu
    # advisingcenter.uiowa.edu:
    #     shortname: advisingcenter
    #     type: custom
    #     git: git@github.com:/its-uofiowa/advisingcenter.uiowa.edu
    # aging.uiowa.edu:
    #     shortname: aging
    #     type: custom
    #     git: git@github.com:/its-uofiowa/aging.uiowa.edu
    # arts.uiowa.edu:
    #     shortname: arts
    #     type: custom
    #     git: git@github.com:/its-uofiowa/arts.uiowa.edu
    # careers.uiowa.edu:
    #     shortname: careers
    #     type: custom
    #     git: git@github.com:/its-uofiowa/careers.uiowa.edu
    # cbb.research.uiowa.edu:
    #     shortname: cbbresearch
    #     type: custom
    #     git: git@github.com:/its-uofiowa/cbb.research.uiowa.edu
    # dining.uiowa.edu:
    #     shortname: dining
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/dining.uiowa.edu'
    # discover.research.uiowa.edu:
    #     shortname: discoverresearch
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/discover.research.uiowa.edu'
    # diversity.uiowa.edu:
    #     shortname: diversity
    #     type: custom
    #     git: git@github.com:/its-uofiowa/diversity.uiowa.edu
    # fye.uiowa.edu:
    #     shortname: fye
    #     type: custom
    #     git: git@github.com:/its-uofiowa/fye.uiowa.edu
    # gao.fo.uiowa.edu:
    #     shortname: gaofo
    #     type: custom
    #     git: git@github.com:/its-uofiowa/gao.fo.uiowa.edu
    # grantwood.uiowa.edu:
    #     shortname: grantwood
    #     type: custom
    #     git: git@github.com:/its-uofiowa/grantwood.uiowa.edu
    # hancher.uiowa.edu:
    #     shortname: hancher
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/hancher.uiowa.edu'
    # honors.uiowa.edu:
    #     shortname: honors
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/honors.uiowa.edu'
    # housing.uiowa.edu:
    #     shortname: housing
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/housing.uiowa.edu'
    # hpc.uiowa.edu:
    #     shortname: hpc
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/hpc.uiowa.edu'
    # ideal.uiowa.edu:
    #     shortname: ideal
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/ideal.uiowa.edu'
    # ip.uiowa.edu:
    #     shortname: ip
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/ip.uiowa.edu'
    # itpmo.uiowa.edu:
    #     shortname: itpmo
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/itpmo.uiowa.edu'
    # its.uiowa.edu:
    #     shortname: its
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/its.uiowa.edu'
    # itsecurity.uiowa.edu:
    #     shortname: itsecurity
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/itsecurity.uiowa.edu'
    # justliving.uiowa.edu:
    #     shortname: justliving
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/justliving.uiowa.edu'
    # law.uiowa.edu:
    #     shortname: law
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/law.uiowa.edu'
    # library.law.uiowa.edu:
    #     shortname: lawlibrary
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/library.law.uiowa.edu'
    # maps.uiowa.edu:
    #     shortname: maps
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/maps.uiowa.edu'
    # mnh.uiowa.edu:
    #     shortname: mnh
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/mnh.uiowa.edu'
    # newstudents.uiowa.edu:
    #     shortname: newstudents
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/newstudents.uiowa.edu'
    # now.uiowa.edu:
    #     shortname: now
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/now.uiowa.edu'
    # nutrition.sports.uiowa.edu:
    #     shortname: nutrition
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/nutrition.sports.uiowa.edu'
    # obermann.uiowa.edu:
    #     shortname: obermann
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/obermann.uiowa.edu'
    # oldcap.uiowa.edu:
    #     shortname: oldcap
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/oldcap.uiowa.edu'
    # oneit.uiowa.edu:
    #     shortname: oneit
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/oneit.uiowa.edu'
    # oniowa.uiowa.edu:
    #     shortname: oniowa
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/oniowa.uiowa.edu'
    # opsmanual.uiowa.edu:
    #     shortname: opsmanual
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/opsmanual.uiowa.edu'
    # outreach.uiowa.edu:
    #     shortname: outreach
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/outreach.uiowa.edu'
    # ovpred.uiowa.edu:
    #     shortname: ovpred
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/ovpred.uiowa.edu'
    # pharmacy.uiowa.edu:
    #     shortname: pharmacy
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/pharmacy.uiowa.edu'
    # president.uiowa.edu:
    #     shortname: president
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/president.uiowa.edu'
    # recserv.uiowa.edu:
    #     shortname: recserv
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/recserv.uiowa.edu'
    # reports.its.uiowa.edu:
    #     shortname: reports
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/reports.its.uiowa.edu'
    # researchpark.uiowa.edu:
    #     shortname: researchpark
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/researchpark.uiowa.edu'
    # strength.sports.uiowa.edu:
    #     shortname: strength
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/strength.sports.uiowa.edu'
    # teach.its.uiowa.edu:
    #     shortname: teachits
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/teach.its.uiowa.edu'
    # theme.uiowa.edu:
    #     shortname: theme
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/theme.uiowa.edu'
    # tier.uiowa.edu:
    #     shortname: tier
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/tier.uiowa.edu'
    # tile.uiowa.edu:
    #     shortname: tile
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/tile.uiowa.edu'
    # tippie.uiowa.edu:
    #     shortname: tippie
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/tippie.uiowa.edu'
    # ubill.fo.uiowa.edu:
    #     shortname: ubillfo
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/ubill.fo.uiowa.edu'
    # uc.uiowa.edu:
    #     shortname: uc
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/uc.uiowa.edu'
    # uiventures.uiowa.edu:
    #     shortname: uiventures
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/uiventures.uiowa.edu'
    # vending.uiowa.edu:
    #     shortname: vending
    #     type: custom
    #     git: 'git@github.com:/its-uofiowa/vending.uiowa.edu'
